// GENERATED by scripts/generate-wire-tables.ts — do not edit by hand.
// Run `pnpm gen:wire-tables` to append new ids. Rows are append-only: never
// reorder or delete one (a removed entity stays as a tombstone).

export const CHARACTER_WIRE: readonly number[] = [
  1203, // Encore
  1102, // Sanhua
  1503, // Verina
  1505, // Shorekeeper
  1603, // Camellya
  1409, // Cartethyia
]

export const WEAPON_WIRE: readonly number[] = [
  21020015, // Emerald of Genesis
  21050016, // Stringmaster
  21050024, // Variation
  21050036, // Stellar Symphony
  21020026, // Red Spring
]

export const ECHO_WIRE: readonly number[] = [
  6000052, // Impermanence Heron
  390080007, // Inferno Rider
  390080005, // Bell-Borne Geochelone
  6000060, // Fallacy of No Return
  6000106, // Reminiscence: Fleurdelys
]

export const ECHO_SET_WIRE: readonly number[] = [
  2, // Molten Rift
  8, // Moonlit Clouds
  7, // Rejuvenating Glow
  6, // Havoc Eclipse
  17, // Windward Pilgrimage
]
