// GENERATED by scripts/generate-wire-tables.ts — do not edit by hand.
// Run `pnpm gen:wire-tables` to append new ids. Rows are append-only: never
// reorder or delete one (a removed entity stays as a tombstone).

export const CHARACTER_WIRE: readonly number[] = [
  1203, // Encore
  1102, // Sanhua
  1503, // Verina
  1505, // Shorekeeper
  1603, // Camellya
  1409, // Cartethyia
]

export const WEAPON_WIRE: readonly number[] = [
  21020015, // Emerald of Genesis
  21050016, // Stringmaster
  21050024, // Variation
  21050036, // Stellar Symphony
  21020026, // Red Spring
]

export const ECHO_WIRE: readonly number[] = [
  6000052, // Impermanence Heron
  390080007, // Inferno Rider
  390080005, // Bell-Borne Geochelone
  6000060, // Fallacy of No Return
  6000106, // Reminiscence: Fleurdelys
]

export const ECHO_SET_WIRE: readonly number[] = [
  2, // Molten Rift
  8, // Moonlit Clouds
  7, // Rejuvenating Glow
  6, // Havoc Eclipse
  17, // Windward Pilgrimage
  16, // Gusts of Welkin
]

// Per-character stage-bearing skill ids, in wire order. A stage's selector
// byte indexes this list (own skills) with the high bit clear.
export const SKILL_WIRE: Record<number, readonly number[]> = {
  1102: [1000501, 1000502, 1000503, 1000506, 1000507, 1000509, 9001, 9002], // Sanhua
  1203: [1000701, 1000702, 1000703, 1000706, 1000707, 1000709, 9001, 9002], // Encore
  1409: [1003501, 1003502, 1003503, 1003506, 1003507, 1003509, 9001, 9002], // Cartethyia
  1503: [1000301, 1000302, 1000303, 1000306, 1000307, 1000309, 9001, 9002], // Verina
  1505: [1002501, 1002502, 1002503, 1002506, 1002507, 1002509, 9001, 9002], // Shorekeeper
  1603: [1001301, 1001302, 1001303, 1001306, 1001307, 1001309, 9001, 9002], // Camellya
}
