import fs from "node:fs/promises"
import path from "node:path"
import { fileURLToPath } from "node:url"
import { ALL_CHARACTERS } from "#/data/characters"
import { ALL_WEAPONS } from "#/data/weapons"
import { ALL_ECHOES } from "#/data/echoes"
import { ALL_ECHO_SETS } from "#/data/echo-sets"
import {
  CHARACTER_WIRE,
  ECHO_SET_WIRE,
  ECHO_WIRE,
  WEAPON_WIRE,
} from "#/lib/share/wire-tables.generated"

const PROJECT_ROOT = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  "..",
)
const OUT = path.join(PROJECT_ROOT, "src/lib/share/wire-tables.generated.ts")

interface Registry {
  name: string
  committed: readonly number[]
  live: { id: number; name: string }[]
}

// Committed order is authoritative and append-only: keep every existing row in
// place, append live ids not already present. A removed id stays as a tombstone.
function merge({ committed, live }: Registry): { id: number; label: string }[] {
  const labelOf = (id: number) =>
    live.find((e) => e.id === id)?.name ?? "removed"
  const rows = committed.map((id) => ({ id, label: labelOf(id) }))
  for (const e of live) {
    if (!committed.includes(e.id)) rows.push({ id: e.id, label: e.name })
  }
  return rows
}

function block(name: string, rows: { id: number; label: string }[]): string {
  const body = rows.map((r) => `  ${r.id}, // ${r.label}`).join("\n")
  return `export const ${name}: readonly number[] = [\n${body}\n]`
}

function render(registries: Record<string, Registry>): string {
  const header = [
    "// GENERATED by scripts/generate-wire-tables.ts — do not edit by hand.",
    "// Run `pnpm gen:wire-tables` to append new ids. Rows are append-only: never",
    "// reorder or delete one (a removed entity stays as a tombstone).",
  ].join("\n")
  const blocks = Object.values(registries).map((reg) =>
    block(reg.name, merge(reg)),
  )
  return `${header}\n\n${blocks.join("\n\n")}\n`
}

const registries: Record<string, Registry> = {
  CHARACTER_WIRE: {
    name: "CHARACTER_WIRE",
    committed: CHARACTER_WIRE,
    live: ALL_CHARACTERS,
  },
  WEAPON_WIRE: {
    name: "WEAPON_WIRE",
    committed: WEAPON_WIRE,
    live: ALL_WEAPONS,
  },
  ECHO_WIRE: { name: "ECHO_WIRE", committed: ECHO_WIRE, live: ALL_ECHOES },
  ECHO_SET_WIRE: {
    name: "ECHO_SET_WIRE",
    committed: ECHO_SET_WIRE,
    live: ALL_ECHO_SETS,
  },
}

const next = render(registries)
const current = await fs.readFile(OUT, "utf8")

if (process.argv.includes("--check")) {
  if (current.trim() !== next.trim()) {
    console.error(
      "wire-tables.generated.ts is stale: a live id is unlisted or a live row was dropped.\nRun `pnpm gen:wire-tables`.",
    )
    process.exit(1)
  }
  console.log("wire-tables.generated.ts up to date.")
} else {
  await fs.writeFile(OUT, next)
  console.log("Wrote src/lib/share/wire-tables.generated.ts")
}
