import fs from "node:fs/promises"
import path from "node:path"
import { fileURLToPath } from "node:url"
import { ALL_CHARACTERS } from "#/data/characters"
import { ALL_WEAPONS } from "#/data/weapons"
import { ALL_ECHOES } from "#/data/echoes"
import { ALL_ECHO_SETS } from "#/data/echo-sets"
import { compileCharacter } from "#/lib/compile-character"
import {
  CHARACTER_WIRE,
  ECHO_SET_WIRE,
  ECHO_WIRE,
  SKILL_WIRE,
  WEAPON_WIRE,
} from "#/lib/share/wire-tables.generated"

const PROJECT_ROOT = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  "..",
)
const OUT = path.join(PROJECT_ROOT, "src/lib/share/wire-tables.generated.ts")

interface Registry {
  committed: readonly number[]
  live: { id: number; name: string }[]
}

// Committed order is authoritative and append-only: keep every existing row in
// place, append live ids not already present. A removed id stays as a tombstone.
function merge({ committed, live }: Registry): { id: number; label: string }[] {
  const labelOf = (id: number) =>
    live.find((e) => e.id === id)?.name ?? "removed"
  const rows = committed.map((id) => ({ id, label: labelOf(id) }))
  for (const e of live) {
    if (!committed.includes(e.id)) rows.push({ id: e.id, label: e.name })
  }
  return rows
}

function block(name: string, reg: Registry): string {
  const body = merge(reg)
    .map((r) => `  ${r.id}, // ${r.label}`)
    .join("\n")
  return `export const ${name}: readonly number[] = [\n${body}\n]`
}

function distinctSkillIds(charId: number): number[] {
  const char = ALL_CHARACTERS.find((c) => c.id === charId)
  if (char === undefined) return []
  const ids: number[] = []
  for (const info of compileCharacter(char).stageIndex.values()) {
    if (!ids.includes(info.skill.id)) ids.push(info.skill.id)
  }
  return ids
}

// Same append-only rule, per character: committed rows first (order preserved),
// new characters appended, new skills appended within each character.
function skillBlock(): string {
  const committedIds = Object.keys(SKILL_WIRE).map(Number)
  const orderedIds = [
    ...committedIds,
    ...ALL_CHARACTERS.map((c) => c.id).filter(
      (id) => !committedIds.includes(id),
    ),
  ]
  const lines = orderedIds.map((charId) => {
    const merged = [...(SKILL_WIRE[charId] ?? [])]
    for (const id of distinctSkillIds(charId)) {
      if (!merged.includes(id)) merged.push(id)
    }
    const name = ALL_CHARACTERS.find((c) => c.id === charId)?.name ?? "removed"
    return `  ${charId}: [${merged.join(", ")}], // ${name}`
  })
  return [
    "// Per-character stage-bearing skill ids, in wire order. A stage's selector",
    "// byte indexes this list (own skills) with the high bit clear.",
    "export const SKILL_WIRE: Record<number, readonly number[]> = {",
    ...lines,
    "}",
  ].join("\n")
}

function render(): string {
  const header = [
    "// GENERATED by scripts/generate-wire-tables.ts — do not edit by hand.",
    "// Run `pnpm gen:wire-tables` to append new ids. Rows are append-only: never",
    "// reorder or delete one (a removed entity stays as a tombstone).",
  ].join("\n")
  const blocks = [
    block("CHARACTER_WIRE", {
      committed: CHARACTER_WIRE,
      live: ALL_CHARACTERS,
    }),
    block("WEAPON_WIRE", { committed: WEAPON_WIRE, live: ALL_WEAPONS }),
    block("ECHO_WIRE", { committed: ECHO_WIRE, live: ALL_ECHOES }),
    block("ECHO_SET_WIRE", { committed: ECHO_SET_WIRE, live: ALL_ECHO_SETS }),
    skillBlock(),
  ]
  return `${header}\n\n${blocks.join("\n\n")}\n`
}

const next = render()
const current = await fs.readFile(OUT, "utf8")

if (process.argv.includes("--check")) {
  if (current.trim() !== next.trim()) {
    console.error(
      "wire-tables.generated.ts is stale: a live id is unlisted or a live row was dropped.\nRun `pnpm gen:wire-tables`.",
    )
    process.exit(1)
  }
  console.log("wire-tables.generated.ts up to date.")
} else {
  await fs.writeFile(OUT, next)
  console.log("Wrote src/lib/share/wire-tables.generated.ts")
}
